### ISSUE TITLE
 [AllureXunitTheory] attribute does not work with MemberData

### ISSUE THREAD

**Issue by mgladchenko** [TinkoffCreditSystems/Allure.XUnit#11]
Exception is thrown
System.InvalidOperationException: The test method expected 1 parameter value, but 0 parameter values were provided.

System.InvalidOperationException
The test method expected 1 parameter value, but 0 parameter values were provided.
  Exception doesn't have a stacktrace

Note: It works fine with InlineData

**Comment by IvanWR1995** [comment]
Hello. Thank your for issue report, @mgladchenko.
We are already working on it, and when we will fix this problem, we will notify you in this thread. There is exist #14 on same problem. 

Faithfully yours,
Ivan

**Comment by JoaoPDias** [comment]
Hello, other situation is when I create a JSONFileData to get my parameters implementing GetData from DataAttribute class. AllureXunitTheory doesn't recognize the test.

``` 
System.InvalidOperationException : The test method expected 1 parameter value, but 0 parameter values were provided.
```
