### ISSUE TITLE
AllureStep, AllureBefore, AllureAfter attributes are missing in the package

### ISSUE THREAD

**Issue by mgladchenko** [TinkoffCreditSystems/Allure.XUnit#12]
Trying to use your code example from README https://github.com/TinkoffCreditSystems/Allure.XUnit/blob/master/src/Allure.Xunit.StepExtensions.Examples/ExampleSteps.cs

Not possible because AllureStep, AllureBefore, AllureAfter attributes are missing in the package

<img width="993" alt="missing_attributes" src="https://user-images.githubusercontent.com/6792291/121682288-9361e800-cac4-11eb-82fa-82036c9c0de4.png">

**Comment by mgladchenko** [comment]
Any suggestions how do I use 'Step' attribute?

**Comment by neparij** [comment]
> Any suggestions how do I use 'Step' attribute?

Hello!
Did you install Allure.Xunit.StepExtensions package?
_AllureStep_, _AllureBefore_, _AllureAfter_ attributes are part of this package.

Best regards,
Nikolay
