### ISSUE TITLE
Attribute usage on classes

### ISSUE THREAD

**Issue by CraigRichards** [TinkoffCreditSystems/Allure.XUnit#13]
Hi,
Nice work on creating this library.

I've worked a lot with NUnit and NUnit.Allure and think their implementation is pretty nice to use. Most notably is the use of attributes at the class level.

Is there any technical reason you did not cater for class-level attributes and is this something you are looking to add?

Cheers
Craig

**Comment by neparij** [comment]
Hello!
Glad to hear you are interested for this project.
I'm currently working on this feature.
You can subscribe to this thread. So you will be notificated when it's done.

Best regards,
Nikolay

**Comment by IvanWR1995** [comment]
Hello!
Thank you for report about this issue. We  have just  resolved this in PR: https://github.com/TinkoffCreditSystems/Allure.XUnit/pull/8 . 
Version 2.0.0 contains this change https://www.nuget.org/packages/Allure.XUnit/2.0.0  

Faithfully yours,
 Ivan
