### ISSUE TITLE
[AllureXunitTheory] MemberData with parameters => no tests discovered

### ISSUE THREAD

**Issue by gedorin** [TinkoffCreditSystems/Allure.XUnit#14]
**Steps to reproduce:**        
[AllureXunitTheory]
[MemberData(nameof(GetData), parameters: "testParam")]
public void InformationApiTests(string scenario, Test test) {}

public static TheoryData GetData(string testParam)
{
//return TheoryData object
}

**Expected result**
Tests are discovered and can be run

**Actual result**
Tests are not discovered and running hangs without error. From cmd, the message is: "No test is available in C:\Repos\test\bin\Debug\net5.0\.\test.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again."

**Comment by Onebitl0st** [comment]
Same for 
[AllureXunit]
public async Task ShouldReturnAccepted()
    {
    // some test thing
    }

**Comment by Onebitl0st** [comment]
@gedorin Probably try to add allureConfig.json ? Helped to me

**Comment by gedorin** [comment]
Thanks @Onebitl0st .. i have it added. Theory is the only one that doesn't work. It's happening on thins repo aswell if you clone it and try running the tests. I fixed the issue by switching to NUnit. :/

**Comment by IvanWR1995** [comment]
Hello. Thank your for issue report, @gedorin .
We are already working on it, and when we will fix this problem, we will notify you in this thread.

Faithfully yours,
Ivan
